name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
       
       # gradlew 실행 권한 부여
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew


    - uses: actions/checkout@v3
    - run: touch ./src/main/resources/application.properties
    - run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties
    - run: cat ./src/main/resources/application.properties
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build -x test
